name: flutter_amazon_clone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.0
  dotted_border: ^2.1.0
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_rating_bar: ^4.0.1
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
